# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
    # npm
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build
    # Aliyun OSS
    - name: Setup Aliyun OSS
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-ap-southeast-1.aliyuncs.com
        access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
    - name: Upload files to OSS
      run: ossutil cp -rf ./dist/ oss://aauth/
